### ISSUE TITLE
Windows 10 encoding

### ISSUE THREAD

**Issue by akam-it** [gen2brain/beeep#11]
Hello, in windows 10 notify window has unreadable characters if string not english

err := beeep.Notify("привет", "привет", "assets/information.png")

**Comment by gen2brain** [comment]
Hello, `beeep` uses https://github.com/go-toast/toast pakage for Windows.
Can you try with example there to see if same thing happens? If same,  not sure what to do, you can perhaps try to add after https://github.com/go-toast/toast/blob/v1/toast.go#L70 `<?xml version="1.0" encoding="utf-8"?>
`
I cannot test currently (need vmware for that).

**Comment by TheTitanrain** [comment]
Same problem.
Example did not show massages entirely.
I tried add this line but that not fixed problem.

**Comment by juja256** [comment]
Win32 API has lots of functions with "W" suffix (along with "A" suffix - ANSI) indicating that character buffers passed into function might be unicode strings. Perhaps it is worth to consider solving problem that way.

**Comment by gen2brain** [comment]
Win32 API is not used for toasts, and probably not possible, that is a new thing. go-toast/toast creates an xml file  and run it with powershell. Maybe it is related to this https://github.com/go-toast/toast/issues/11 , can someone add BOM and try with it?

**Comment by gen2brain** [comment]
This should be fixed with https://github.com/go-toast/toast/pull/16

**Comment by popstas** [comment]
Created temp fork with master branch of go-toast/toast - https://github.com/viasite/beeep

**Comment by gen2brain** [comment]
Changed in https://github.com/gen2brain/beeep/commit/13046a26d502f021dfa3f65f40f3d5015ab9ffb2

**Comment by popstas** [comment]
Thank you!
