### ISSUE TITLE
Mac notification doesn't fulfil interface

### ISSUE THREAD

**Issue by boedy** [gen2brain/beeep#15]
Current implementation on Mac does not support custom images. How about using https://github.com/deckarep/gosx-notifier as Darwin notifier?

**Comment by gen2brain** [comment]
I don't like it, it embeds whole app/binary in source code.

**Comment by boedy** [comment]
I see I overlooked issue https://github.com/gen2brain/beeep/issues/2 where you already discussed gosx-notifier.

Would be good to to update to readme that custom images are not part of the Darwin api.
