### ISSUE TITLE
Its not possible to create toast notification as service

### ISSUE THREAD

**Issue by ericrange** [gen2brain/beeep#16]

**Comment by gen2brain** [comment]
Can you describe what you meant with notification as service, is it a Windows only thing? How will that work on macOS and Linux, and is it related to https://github.com/gen2brain/beeep/issues/10 .

**Comment by ericrange** [comment]
its windows thing. a service dont have access to a active window user session. its possible but it needs some windows-dll magic :(
the toast notification apears if you start the program as a user. but not, in a service context.

**Comment by martinlindhe** [comment]
@ericrange services normally don't use notifications, but rather write to the event log.

https://godoc.org/golang.org/x/sys/windows/svc/eventlog
