### ISSUE TITLE
Icon not displayed

### ISSUE THREAD

**Issue by 0xfederama** [gen2brain/beeep#39]
I used Alert to send a notification, I packaged the app with https://github.com/machinebox/appify and then created a dmg following https://medium.com/@mattholt/packaging-a-go-application-for-macos-f7084b00f6b5. Still no icon when sending notification. 
I tried the app on the latest version of MacOS.

**Comment by gen2brain** [comment]
Notifications on macOS use `osascript display notification`, every .app can have the icon and that is what was used/shown in earlier mac versions. You can check and search with that info, this package cannot do much about your issue.

**Comment by 0xfederama** [comment]
I said it cause I read that to display the icon I should bundle the app with an icon. I think that doesn't work anymore

**Comment by gen2brain** [comment]
Looks like it doesn't work anymore, by this comment https://apple.stackexchange.com/questions/106904/change-the-icon-of-an-applescript-called-notification#comment499121_108558
