### ISSUE TITLE
Macos icon

### ISSUE THREAD

**Issue by That-Dude** [gen2brain/beeep#40]
In the readme it states **"For icons to show up when using Alert() or Notify(), you will need to bundle your application with a app icon."** but I'm not sure how that should work.

I've created an app bundle like so:

```
> tree danotify.app

danotify.app
└── Contents
    ├── MacOS
    │   └── danotify
    ├── Resources
    │   └── icon.icns
    └── info.plist

3 directories, 3 files
```
And the app has the icon I assigned, but notifications are still the default 'pen on paper' icon

**Comment by gen2brain** [comment]
There was already issue about this, it seems it doesn't work anymore https://github.com/gen2brain/beeep/issues/39 .

**Comment by That-Dude** [comment]
OK thanks. Maybe consider removing that sentence from the bottom of the read.me as it's no longer valid.
