### ISSUE TITLE
Alert() `title` and `message` not escaped when using AppleScript on macOS

### ISSUE THREAD

**Issue by nervo** [gen2brain/beeep#48]
Notify() part has been fixed by https://github.com/gen2brain/beeep/pull/47, but not Alert() :)

See: https://github.com/gen2brain/beeep/issues/37#issuecomment-1147122542

**Comment by gen2brain** [comment]
Can you send a PR?

**Comment by nervo** [comment]
sure :) https://github.com/gen2brain/beeep/pull/49
